### ISSUE TITLE
ffmpeg-normalize can't handle spaces ininstall filepath

### ISSUE THREAD

**Issue by shortnick** [slhck/audio-normalize#12]
The space in [folder name]Program Files broke usage. 
Had to move ffmpeg to C:

**Comment by michaelcrossland** [comment]
Don't fell bad under windows 10 you have to install Python at C:\ otherwise python will not work because it can not put anything into the Programs File folders or the (x86) because of the new BS that MS has come up with.
Wish the Python site would said something about that at the time of download. Good thing I remembered about that little got you.

**Comment by slhck** [comment]
Think I fixed it, works for me under Windows with Cygwin with ffmpeg in `Program Files`.
